default: &default
  adapter: sqlite3
  #adapter: postgresql
  encoding: unicode
  host: db
  #host: localhost
  # TODO:この情報は何かしらの方法を使って隠蔽する。
  sername: sqlite3
  #username: postgresql
  password: sqlite3
  pool: 5
  
development:
  <<: *default
  database: household_account_on_rails_development

test:
  <<: *default
  database: household_account_on_rails_test
